//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.29 at 11:11:18 PM MSK 
//


package by.kunavich.xmlTask.entity;;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.Date;
import java.util.Objects;


/**
 * <p>Java class for Greeting_Card complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Greeting_Card">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.com/cards}Cards">
 *       &lt;attribute name="greeting-date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Greeting_Card")
public class GreetingCard
    extends Cards
{

    @XmlAttribute(name = "greeting-date")
    @XmlSchemaType(name = "date")
    protected Date greetingDate;

    /**
     * Gets the value of the greetingDate property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getGreetingDate() {
        return greetingDate;
    }

    /**
     * Sets the value of the greetingDate property.
     *
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setGreetingDate(Date value) {
        this.greetingDate = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GreetingCard)) return false;
        if (!super.equals(o)) return false;
        GreetingCard that = (GreetingCard) o;
        return Objects.equals(greetingDate, that.greetingDate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), greetingDate);
    }
}
