//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.29 at 11:11:18 PM MSK 
//


package by.kunavich.xmlTask.entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Theme.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Theme">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="landscape"/>
 *     &lt;enumeration value="nature"/>
 *     &lt;enumeration value="people"/>
 *     &lt;enumeration value="religion"/>
 *     &lt;enumeration value="sports"/>
 *     &lt;enumeration value="architecture"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Theme")
@XmlEnum
public enum Theme {

    @XmlEnumValue("landscape")
    LANDSCAPE("landscape"),
    @XmlEnumValue("nature")
    NATURE("nature"),
    @XmlEnumValue("people")
    PEOPLE("people"),
    @XmlEnumValue("religion")
    RELIGION("religion"),
    @XmlEnumValue("sports")
    SPORTS("sports"),
    @XmlEnumValue("architecture")
    ARCHITECTURE("architecture");
    private final String value;

    Theme(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Theme fromValue(String v) {
        for (Theme c: Theme.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
